version: "1.0"

services:
  backend:
    image: tmiskowicz/p-android-ktor
    ports:
      - 8080:8080

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "backend:8080"]